=== Eliaspam/XML_DB/testing/Full.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:test="http://example.com/Quatsch"
           targetNamespace="http://example.com/Quatsch">
    <xs:import/>

    <!-- This is the full DB -->
    <xs:element name="Ferienwohnungsvermittlungsagentur">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Kunden" type="test:Kunden">
                    <xs:key name="KundenNr">
                        <xs:selector xpath="Kunde"/>
                        <xs:field xpath="@ID"/>
                    </xs:key>
                </xs:element>
                <xs:element name="Ferienwohnungen" type="test:wohnungenType">
                    <xs:key name="WohnungsNr">
                        <xs:selector xpath="Wohnung"/>
                        <xs:field xpath="@ID"/>
                    </xs:key>
                </xs:element>
                <xs:element name="Belegungen" type="test:belegungenType">
                    <xs:key name="BelegungsNr">
                        <xs:selector xpath="Belegung"/>
                        <xs:field xpath="@ID"/>
                    </xs:key>
                    <xs:keyref name="Kunde" refer="KundenNr">
                        <xs:selector xpath="Belegung"/>
                        <xs:field xpath="KundenNr"/>
                    </xs:keyref>
                    <xs:keyref name="Wohnung" refer="WohnungsNr">
                        <xs:selector xpath="Belegung"/>
                        <xs:field xpath="WohnungsNr"/>
                    </xs:keyref>
                </xs:element>
                <xs:element name="Rechnungen" type="test:rechnungenType">
                    <xs:key name="RechnungsNr">
                        <xs:selector xpath="Rechnung"/>
                        <xs:field xpath="@ID"/>
                    </xs:key>
                    <xs:keyref name="Belegung" refer="BelegungsNr">
                        <xs:selector xpath="Rechnungen/Rechnung"/>
                        <xs:field xpath="BelegungsNr"/>
                    </xs:keyref>
                </xs:element>
                <xs:element name="Länder" type="test:länderType">
                    <xs:key name="ISO">
                        <xs:selector xpath="Land"/>
                        <xs:field xpath="@ISO"/>
                    </xs:key>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- References -->
    </xs:element>

    <!-- Complex types -->
    <xs:complexType name="Kunden">
        <xs:sequence>
            <!-- The Kunden Element holds unlimited 'Kunde' elements -->
            <xs:element name="Kunde" type="test:kundeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="kundeType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Vorname" type="xs:string"/>
            <xs:element name="Geburtsdatum" type="xs:date"/>
            <xs:element name="Adresse" type="test:adresseType"/>
            <xs:element name="Email" type="xs:string"/>
            <xs:element name="Telefon" type="xs:string"/>
            <xs:element name="Bankverbindung" type="test:bankverbindungType">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="adresseType">
        <xs:sequence>
            <xs:element name="Land" type="xs:string"/>
            <xs:element name="Ort" type="xs:string"/>
            <xs:element name="PLZ" type="xs:string"/>
            <xs:element name="Straße" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="bankverbindungType">
        <xs:sequence>
            <xs:element name="IBAN" type="xs:string"/>
            <xs:element name="Kontonummer" type="xs:string"/>
            <xs:element name="Bankleitzahl" type="xs:string"/>
            <xs:element name="BIC" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="wohnungenType">
        <xs:sequence>
            <xs:element name="Wohnung" type="test:wohnungType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="wohnungType">
        <xs:sequence>
            <xs:element name="Preis" type="xs:decimal"/>
            <xs:element name="Größe" type="xs:int"/>
            <xs:element name="ZimmerAnzahl" type="xs:int"/>
            <xs:element name="Bilder" type="test:bilderType" minOccurs="0"/>
            <xs:element name="Beschreibung" type="xs:string"/>
            <xs:element name="Adresse" type="test:adresseType"/>
            <xs:element name="Zusatzaustattung" type="test:ausstattungType" minOccurs="0">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="bilderType">
        <xs:sequence>
            <xs:element name="Bild" type="test:bildType" maxOccurs="5"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="bildType">
        <xs:sequence>
            <xs:element name="Pfad" type="xs:anyURI" maxOccurs="5"/>
            <xs:element name="Titel" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ausstattungType">
        <xs:sequence>
            <xs:element name="Austattung" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="belegungenType">
        <xs:sequence>
            <xs:element name="Belegung" type="test:belegungType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="belegungType">
        <xs:sequence>
            <xs:element type="xs:int" name="KundenNr"/>
            <xs:element type="xs:int" name="WohnungsNr"/>
            <xs:element type="xs:date" name="von"/>
            <xs:element type="xs:date" name="bis"/>
            <xs:element type="xs:date" name="Belegungsdatum"/>
        </xs:sequence>
        <xs:attribute name="Art" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Reservierung"/>
                    <xs:enumeration value="Buchungen"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ID" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="rechnungenType">
        <xs:sequence>
            <xs:element name="Rechnung" type="test:rechnungType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="rechnungType">
        <xs:sequence>
            <xs:element name="BelegungsNr" type="xs:int"/>
            <xs:element name="Betrag" type="xs:decimal"/>
            <xs:element name="Belegungsdatum" type="xs:date"/>
            <xs:element name="Zahlungseingang" type="xs:date" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="länderType">
        <xs:sequence>
            <xs:element name="Land" type="test:landType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="landType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ISO" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== Eliaspam/XML_DB/testing/DB.xml
<?xml version="1.1" encoding="UTF-8"?>

<Ferienwohnungsvermittlungsagentur
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/Quatsch Full.xsd"
        xmlns="http://example.com/Quatsch">
    <Kunden>
        <Kunde ID="1">
            <Name>Karl</Name>
            <Vorname>Napf</Vorname>
            <Adresse>
                <Land>Deutschland</Land>
                <Ort>Konstanz</Ort>
                <PLZ>78467</PLZ>
                <Straße>Reutestraße 104</Straße>
            </Adresse>
            <Email>knapf@gmx.de</Email>
            <Telefon>07531-123456</Telefon>
            <Bankverbindung>
                <IBAN>DE85692717230007823212</IBAN>
                <Kontonummer>7823212</Kontonummer>
                <Bankleitzahl>69271723</Bankleitzahl>
                <BIC>KARSDE66XXX</BIC>
            </Bankverbindung>
        </Kunde>
        <Kunde ID="2">
            <Name>Meier</Name>
            <Vorname>Hans</Vorname>
            <Adresse>
                <Land>Deutschland</Land>
                <Ort>Heidelberg</Ort>
                <PLZ>69115</PLZ>
                <Straße>Hauptstraße 12</Straße>
            </Adresse>
            <Email>meier.hans@t-online.de</Email>
            <Telefon>06221-999888</Telefon>
            <Bankverbindung>
                <IBAN>DE83692717230008929368</IBAN>
                <Kontonummer>7823212</Kontonummer>
                <Bankleitzahl>32793968</Bankleitzahl>
                <BIC>BARSDE77XXX</BIC>
            </Bankverbindung>
        </Kunde>
    </Kunden>
    <Ferienwohnungen>
        <Wohnung ID="1">
            <Preis>349</Preis>
            <Größe>200</Größe>
            <ZimmerAnzahl>6</ZimmerAnzahl>
            <Bilder>
                <Bild>1_1.jpg, Aussenansicht</Bild>
                <Bild>1_2.jpg, Innenansicht</Bild>
            </Bilder>
            <Beschreibung>Finka</Beschreibung>
            <Adresse>
                <Land>Türkei</Land>
                <Ort>Öludeniz</Ort>
                <PLZ>2349</PLZ>
                <Straße>Highway 5</Straße>
            </Adresse>
        </Wohnung>
    </Ferienwohnungen>
    <Belegungen></Belegungen>
    <Rechnungen></Rechnungen>
    <Länder>
        <Land>
            <ISO>DE</ISO>
            <Name>Deutschland</Name>
        </Land>
        <Land>
            <ISO>TR</ISO>
            <Name>Türkei</Name>
        </Land>
    </Länder>
</Ferienwohnungsvermittlungsagentur>
