=== Eliaspam/XML_DB/2_Datendefinition/Ferienwohnungsvermittlungsagentur.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:test="http://example.com/Quatsch"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           vc:minVersion="1.1"
           targetNamespace="http://example.com/Quatsch">

    <!--  This is the full DB  -->
    <xs:element name="Ferienwohnungsvermittlungsagentur">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Kunden" type="test:Kunden"/>
                <xs:element name="Ferienwohnungen" type="test:wohnungenType"/>
                <xs:element name="Belegungen" type="test:belegungenType"/>
                <xs:element name="Rechnungen" type="test:rechnungenType"/>
                <xs:element name="Länder" type="test:länderType"/>
            </xs:sequence>
        </xs:complexType>
        <!--  Keys  -->
        <!--  Kunde  -->
        <xs:key name="KundenNr">
            <xs:selector xpath="Kunden/Kunde"/>
            <xs:field xpath="@ID"/>
        </xs:key>
        <xs:key name="Email">
            <xs:selector xpath="Kunden/Kunde"/>
            <xs:field xpath="Email"/>
        </xs:key>
        <!--  Bankverbindung  -->
        <xs:key name="IBAN">
            <xs:selector xpath="Kunden/Kunde/Bankverbindung"/>
            <xs:field xpath="IBAN"/>
        </xs:key>
        <xs:key name="Bankverbindung-BIC">
            <xs:selector xpath="Kunden/Kunde/Bankverbindung"/>
            <xs:field xpath="Kontonummer"/>
            <xs:field xpath="BIC"/>
        </xs:key>
        <xs:key name="Bankverbindung-BLZ">
            <xs:selector xpath="Kunden/Kunde/Bankverbindung"/>
            <xs:field xpath="Kontonummer"/>
            <xs:field xpath="BLZ"/>
        </xs:key>
        <!--  Wohnung  -->
        <xs:key name="WohnungsNr">
            <xs:selector xpath="Ferienwohnungen/Wohnung"/>
            <xs:field xpath="@ID"/>
        </xs:key>
        <!--  Belegung  -->
        <xs:key name="BelegungsNr">
            <xs:selector xpath="Belegungen/Belegung"/>
            <xs:field xpath="@ID"/>
        </xs:key>
        <!--  Rechnung  -->
        <xs:key name="RechnungsNr">
            <xs:selector xpath="Rechnungen/Rechnung"/>
            <xs:field xpath="@ID"/>
        </xs:key>
        <!--  Land  -->
        <xs:key name="ISO">
            <xs:selector xpath="Länder/Land"/>
            <xs:field xpath="@ISO"/>
        </xs:key>
        <!--  Keyrefs  -->
        <!--  Belegung  -->
        <xs:keyref name="Kunde" refer="test:KundenNr">
            <xs:selector xpath="Belegungen/Belegung"/>
            <xs:field xpath="KundenNr"/>
        </xs:keyref>
        <xs:keyref name="Wohnung" refer="test:WohnungsNr">
            <xs:selector xpath="Belegungen/Belegung"/>
            <xs:field xpath="WohnungsNr"/>
        </xs:keyref>
        <!--  Rechnung  -->
        <xs:keyref name="Belegung" refer="test:BelegungsNr">
            <xs:selector xpath="Rechnungen/Rechnung"/>
            <xs:field xpath="BelegungsNr"/>
        </xs:keyref>
        <xs:keyref name="Land-Kunde" refer="test:ISO">
            <xs:selector xpath="Kunden/Kunde/Adresse"/>
            <xs:field xpath="Land"/>
        </xs:keyref>
        <xs:keyref name="Land-Wohnung" refer="test:ISO">
            <xs:selector xpath="Ferienwohnungen/Wohnung/Adresse"/>
            <xs:field xpath="Land"/>
        </xs:keyref>
    </xs:element>

    <!--  Complex types  -->
    <xs:complexType name="Kunden">
        <xs:sequence>
            <!--  The Kunden Element holds unlimited 'Kunde' elements  -->
            <xs:element name="Kunde" type="test:kundeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="kundeType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Vorname" type="xs:string"/>
            <xs:element name="Geburtsdatum" type="xs:date"/>
            <xs:element name="Adresse" type="test:adresseType"/>
            <xs:element name="Email" type="xs:string"/>
            <xs:element name="Telefon" type="xs:string"/>
            <xs:element name="Bankverbindung" type="test:bankverbindungType"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="adresseType">
        <xs:sequence>
            <xs:element name="Land" type="xs:string"/>
            <xs:element name="Ort" type="xs:string"/>
            <xs:element name="PLZ" type="xs:string"/>
            <xs:element name="Straße" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="bankverbindungType">
        <xs:sequence>
            <xs:element name="IBAN" type="xs:string"/>
            <xs:element name="Kontonummer" type="xs:string"/>
            <xs:element name="BLZ" type="xs:string"/>
            <xs:element name="BIC" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="wohnungenType">
        <xs:sequence>
            <xs:element name="Wohnung" type="test:wohnungType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="wohnungType">
        <xs:sequence>
            <xs:element name="Preis">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minExclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Größe">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minExclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ZimmerAnzahl">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minExclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Bilder" type="test:bilderType" minOccurs="0"/>
            <xs:element name="Beschreibung" type="xs:string"/>
            <xs:element name="Adresse" type="test:adresseType"/>
            <xs:element name="Zusatzaustattung" type="test:ausstattungType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="bilderType">
        <xs:sequence>
            <xs:element name="Bild" type="test:bildType" maxOccurs="4"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="bildType">
        <xs:sequence>
            <xs:element name="Pfad" type="xs:anyURI"/>
            <xs:element name="Titel" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ausstattungType">
        <xs:sequence>
            <xs:element name="Austattung" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="belegungenType">
        <xs:sequence>
            <xs:element name="Belegung" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="test:belegungType">
                            <xs:assert test="(. = 'Reservierung' and $value = 'Belegung') or . = $value"/>
                            <xs:assert test="bis gt von"/>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!--  Todo: Reservierung to Buchung, but not Buchung to Reservierung  -->
    <xs:complexType name="belegungType">
        <xs:sequence>
            <xs:element name="KundenNr" type="xs:int"/>
            <xs:element name="WohnungsNr" type="xs:int"/>
            <xs:element name="von" type="xs:date"/>
            <xs:element name="bis" type="xs:date"/>
            <xs:element name="Belegungsdatum" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="Art" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Reservierung"/>
                    <xs:enumeration value="Buchung"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ID" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="rechnungenType">
        <xs:sequence>
            <xs:element name="Rechnung" type="test:rechnungType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="rechnungType">
        <xs:sequence>
            <xs:element name="BelegungsNr" type="xs:int"/>
            <xs:element name="Betrag" type="xs:decimal"/>
            <xs:element name="Rechnungsdatum" type="xs:date"/>
            <xs:element name="Zahlungseingang" type="xs:date" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="länderType">
        <xs:sequence>
            <xs:element name="Land" type="test:landType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="landType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ISO" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== Eliaspam/XML_DB/5_Reports/1/B/DB.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet href="Uebersicht_Kunden_HTML.xsl" type="text/xsl"?>

<test:Ferienwohnungsvermittlungsagentur
        xmlns:test="http://example.com/Quatsch"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/Quatsch /2_Datendefinition/Ferienwohnungsvermittlungsagentur.xsd">

    <Kunden>
        <Kunde ID="1">
            <Name>Karl</Name>
            <Vorname>Napf</Vorname>
            <Geburtsdatum>1960-01-01</Geburtsdatum>
            <Adresse>
                <Land>DE</Land>
                <Ort>Konstanz</Ort>
                <PLZ>78467</PLZ>
                <Straße>Reutestraße 104</Straße>
            </Adresse>
            <Email>knapf@gmx.de</Email>
            <Telefon>07531-123456</Telefon>
            <Bankverbindung>
                <IBAN>DE85692717230007823212</IBAN>
                <Kontonummer>7823212</Kontonummer>
                <BLZ>69271723</BLZ>
                <BIC>KARSDE66XXX</BIC>
            </Bankverbindung>
        </Kunde>
        <Kunde ID="2">
            <Name>Meier</Name>
            <Vorname>Hans</Vorname>
            <Geburtsdatum>1975-01-02</Geburtsdatum>
            <Adresse>
                <Land>DE</Land>
                <Ort>Heidelberg</Ort>
                <PLZ>69115</PLZ>
                <Straße>Hauptstraße 12</Straße>
            </Adresse>
            <Email>meier.hans@t-online.de</Email>
            <Telefon>06221-999888</Telefon>
            <Bankverbindung>
                <IBAN>DE83692717230008929368</IBAN>
                <Kontonummer>7823212</Kontonummer>
                <BLZ>32793968</BLZ>
                <BIC>BARSDE77XXX</BIC>
            </Bankverbindung>
        </Kunde>
        <Kunde ID="3">
            <Name>Huber</Name>
            <Vorname>Franz</Vorname>
            <Geburtsdatum>1980-01-03</Geburtsdatum>
            <Adresse>
                <Land>DE</Land>
                <Ort>Stuttgart</Ort>
                <PLZ>70713</PLZ>
                <Straße>Schlossstraße 54</Straße>
            </Adresse>
            <Email>huber@t-online.de</Email>
            <Telefon>0711-554673</Telefon>
            <Bankverbindung>
                <IBAN>DE85692717230001347291</IBAN>
                <Kontonummer>1347291</Kontonummer>
                <BLZ>69271723</BLZ>
                <BIC>KARSDE66XXX</BIC>
            </Bankverbindung>
        </Kunde>
        <Kunde ID="4">
            <Name>Eber</Name>
            <Vorname>Klaus</Vorname>
            <Geburtsdatum>1985-01-06</Geburtsdatum>
            <Adresse>
                <Land>CH</Land>
                <Ort>Bern</Ort>
                <PLZ>3001</PLZ>
                <Straße>Alpenstraße 11</Straße>
            </Adresse>
            <Email>eber@bluewin.ch</Email>
            <Telefon>+41-171-9864785</Telefon>
            <Bankverbindung>
                <IBAN>CH85692717230008792978</IBAN>
                <Kontonummer>8792978</Kontonummer>
                <BLZ>29788431</BLZ>
                <BIC>MEMECH88XXX</BIC>
            </Bankverbindung>
        </Kunde>
        <Kunde ID="5">
            <Name>Meier</Name>
            <Vorname>Egon</Vorname>
            <Geburtsdatum>1990-01-05</Geburtsdatum>
            <Adresse>
                <Land>CH</Land>
                <Ort>Zürich</Ort>
                <PLZ>8001</PLZ>
                <Straße>Seeweg 23</Straße>
            </Adresse>
            <Email>meier@gmail.com</Email>
            <Telefon>+41-171-9864786</Telefon>
            <Bankverbindung>
                <IBAN>CH85692717230009082780</IBAN>
                <Kontonummer>9082780</Kontonummer>
                <BLZ>87890271</BLZ>
                <BIC>KONSCH12XXX</BIC>
            </Bankverbindung>
        </Kunde>
        <Kunde ID="6">
            <Name>Knopf</Name>
            <Vorname>Jim</Vorname>
            <Geburtsdatum>1995-01-06</Geburtsdatum>
            <Adresse>
                <Land>DE</Land>
                <Ort>Konstanz</Ort>
                <PLZ>78462</PLZ>
                <Straße>Rheingutstraße 14</Straße>
            </Adresse>
            <Email>jim.knopf@gmx.net</Email>
            <Telefon>0171-9876543</Telefon>
            <Bankverbindung>
                <IBAN>DE85692717230007322890</IBAN>
                <Kontonummer>7322890</Kontonummer>
                <BLZ>69271723</BLZ>
                <BIC>KARSDE66XXX</BIC>
            </Bankverbindung>
        </Kunde>
    </Kunden>
    <Ferienwohnungen>
        <Wohnung ID="1">
            <Preis>349</Preis>
            <Größe>200</Größe>
            <ZimmerAnzahl>6</ZimmerAnzahl>
            <Bilder>
                <Bild>
                    <Pfad>1_2.jpg</Pfad>
                    <Titel>Innenansicht</Titel></Bild>
                <Bild>
                    <Pfad>1_1.jpg</Pfad>
                    <Titel>Aussenansicht</Titel>
                </Bild>
            </Bilder>
            <Beschreibung>Finka</Beschreibung>
            <Adresse>
                <Land>TR</Land>
                <Ort>Öludeniz</Ort>
                <PLZ>2349</PLZ>
                <Straße>Highway 5</Straße>
            </Adresse>
            <Zusatzaustattung>
                <Austattung>Schwimmbad</Austattung>
                <Austattung>Sauna</Austattung>
            </Zusatzaustattung>
        </Wohnung>
        <Wohnung ID="2">
            <Preis>120</Preis>
            <Größe>45</Größe>
            <ZimmerAnzahl>2</ZimmerAnzahl>
            <Bilder>
                <Bild>
                    <Pfad>2_1.jpg</Pfad>
                    <Titel>Aussenansicht</Titel>
                </Bild>
                <Bild>
                    <Pfad>2_2.jpg</Pfad>
                    <Titel>Innenansicht</Titel>
                </Bild>
            </Bilder>
            <Beschreibung>Ferienwohnung mit Seeblick</Beschreibung>
            <Adresse>
                <Land>DE</Land>
                <Ort>Konstanz</Ort>
                <PLZ>78461</PLZ>
                <Straße>Markgrafenstraße 33</Straße>
            </Adresse>
        </Wohnung>
        <Wohnung ID="3">
            <Preis>249</Preis>
            <Größe>150</Größe>
            <ZimmerAnzahl>3</ZimmerAnzahl>
            <Beschreibung>im Schnee</Beschreibung>
            <Adresse>
                <Land>CH</Land>
                <Ort>Chur</Ort>
                <PLZ>2234</PLZ>
                <Straße>Zur Piste 189</Straße>
            </Adresse>
            <Zusatzaustattung>
                <Austattung>Sauna</Austattung>
            </Zusatzaustattung>
        </Wohnung>
        <Wohnung ID="4">
            <Preis>249</Preis>
            <Größe>100</Größe>
            <ZimmerAnzahl>4</ZimmerAnzahl>
            <Beschreibung>direkt am Meer</Beschreibung>
            <Adresse>
                <Land>FR</Land>
                <Ort>Bordeaux</Ort>
                <PLZ>8234</PLZ>
                <Straße>rue Monsieur 980</Straße>
            </Adresse>
        </Wohnung>
        <Wohnung ID="5">
            <Preis>289</Preis>
            <Größe>110</Größe>
            <ZimmerAnzahl>3</ZimmerAnzahl>
            <Bilder>
                <Bild>
                    <Pfad>5_1.gif</Pfad>
                    <Titel>Garage</Titel>
                </Bild>
            </Bilder>
            <Beschreibung>direkt am Park</Beschreibung>
            <Adresse>
                <Land>FR</Land>
                <Ort>Disneyland</Ort>
                <PLZ>8787</PLZ>
                <Straße>rue de gaulle 22</Straße>
            </Adresse>
            <Zusatzaustattung>
                <Austattung>Kinderbetreuung</Austattung>
                <Austattung>Schwimmbad</Austattung>
            </Zusatzaustattung>
        </Wohnung>
        <Wohnung ID="6">
            <Preis>549</Preis>
            <Größe>70</Größe>
            <ZimmerAnzahl>2</ZimmerAnzahl>
            <Beschreibung>mit Blick auf Eiffelturm</Beschreibung>
            <Adresse>
                <Land>FR</Land>
                <Ort>Paris</Ort>
                <PLZ>8792</PLZ>
                <Straße>rue de la Maison Blanche 32</Straße>
            </Adresse>
            <Zusatzaustattung>
                <Austattung>Schwimmbad</Austattung>
            </Zusatzaustattung>
        </Wohnung>
        <Wohnung ID="7">
            <Preis>159</Preis>
            <Größe>110</Größe>
            <ZimmerAnzahl>6</ZimmerAnzahl>
            <Beschreibung>Dachterrassewohnung zentral</Beschreibung>
            <Adresse>
                <Land>FR</Land>
                <Ort>Paris</Ort>
                <PLZ>8792</PLZ>
                <Straße>rue liberte 78</Straße>
            </Adresse>
            <Zusatzaustattung>
                <Austattung>Schwimmbad</Austattung>
            </Zusatzaustattung>
        </Wohnung>
        <Wohnung ID="8">
            <Preis>249</Preis>
            <Größe>200</Größe>
            <ZimmerAnzahl>12</ZimmerAnzahl>
            <Bilder>
                <Bild>
                    <Pfad>8.jpg</Pfad>
                    <Titel>Dachterrasse</Titel>
                </Bild>
            </Bilder>
            <Beschreibung>zweigeschoessiges Haus</Beschreibung>
            <Adresse>
                <Land>TR</Land>
                <Ort>Antalya</Ort>
                <PLZ>2321</PLZ>
                <Straße>Strandweg 90</Straße>
            </Adresse>
            <Zusatzaustattung>
                <Austattung>Sat-TV</Austattung>
                <Austattung>Reinigung</Austattung>
                <Austattung>Dachterrasse</Austattung>
            </Zusatzaustattung>
        </Wohnung>
        <Wohnung ID="9">
            <Preis>159</Preis>
            <Größe>111</Größe>
            <ZimmerAnzahl>5</ZimmerAnzahl>
            <Beschreibung>Topvilla am Strand</Beschreibung>
            <Adresse>
                <Land>TR</Land>
                <Ort>Antalya</Ort>
                <PLZ>2321</PLZ>
                <Straße>Strandweg 91</Straße>
            </Adresse>
            <Zusatzaustattung>
