=== Eliaspam/XML_DB/5_Reports/2/A/Offene_Rechnungen.dtd
<!ELEMENT OffeneRechnungen (Rechnung*)>
        <!ELEMENT Rechnung (RechnungsNr, Rechnungsdatum, Rechnungsbetrag, Buchung, Kunde)>
        <!ELEMENT RechnungsNr (#PCDATA)>
        <!ELEMENT Rechnungsdatum (#PCDATA)>
        <!ELEMENT Rechnungsbetrag (#PCDATA)>

        <!ELEMENT Buchung (BuchungsNr, von, bis, Ferienwohnung)>
        <!ATTLIST Buchung Datum CDATA #REQUIRED>
        <!ELEMENT BuchungsNr (#PCDATA)>
        <!ELEMENT von (#PCDATA)>
        <!ELEMENT bis (#PCDATA)>

        <!ELEMENT Ferienwohnung (FerienwohnungsNr, Beschreibung)>
        <!ELEMENT FerienwohnungsNr (#PCDATA)>
        <!ELEMENT Beschreibung (#PCDATA)>

        <!ELEMENT Kunde (KundenNr, Vorname, Nachname, Email, Telefon, Adresse, Bankverbindung)>
        <!ELEMENT KundenNr (#PCDATA)>
        <!ELEMENT Vorname (#PCDATA)>
        <!ELEMENT Nachname (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Telefon (#PCDATA)>

        <!ELEMENT Adresse (Straße, PLZ, Ort, Land)>
        <!ELEMENT Straße (#PCDATA)>
        <!ELEMENT PLZ (#PCDATA)>
        <!ELEMENT Ort (#PCDATA)>
        <!ELEMENT Land (#PCDATA)>

        <!ELEMENT Bankverbindung (IBAN, BIC)>
        <!ELEMENT IBAN (#PCDATA)>
        <!ELEMENT BIC (#PCDATA)>

=== Eliaspam/XML_DB/5_Reports/2a.xml
<!DOCTYPE OffeneRechnungen SYSTEM
        "/Users/eliaspampuch/Study/Semester_4/DBIS_2/XML_Project/5_Reports/2/A/Offene_Rechnungen.dtd">
<OffeneRechnungen>
    <Rechnung>
        <RechnungsNr>2</RechnungsNr>
        <Rechnungsdatum>2016-02-26</Rechnungsdatum>
        <Rechnungsbetrag>549</Rechnungsbetrag>
        <Buchung Datum="2016-02-09">
            <BuchungsNr>4</BuchungsNr>
            <von>2016-07-04</von>
            <bis>2016-07-05</bis>
            <Ferienwohnung>
                <FerienwohnungsNr>6</FerienwohnungsNr>
                <Beschreibung>mit Blick auf Eiffelturm</Beschreibung>
            </Ferienwohnung>
        </Buchung>
        <Kunde>
            <KundenNr>4</KundenNr>
            <Vorname>Klaus</Vorname>
            <Nachname>Eber</Nachname>
            <Email>eber@bluewin.ch</Email>
            <Telefon>+41-171-9864785</Telefon>
            <Adresse>
                <Straße>Alpenstraße 11</Straße>
                <PLZ>3001</PLZ>
                <Ort>Bern</Ort>
                <Land>Schweiz</Land>
            </Adresse>
            <Bankverbindung>
                <IBAN>CH85692717230008792978</IBAN>
                <BIC>MEMECH88XXX</BIC>
            </Bankverbindung>
        </Kunde>
    </Rechnung>
</OffeneRechnungen>
